# Enable logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_DEFERRED=y

# Enable GPIO and I2C
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2C_INIT_PRIORITY=50

# Enable sensor subsystem
CONFIG_SENSOR=y
CONFIG_SENSOR_INIT_PRIORITY=70
CONFIG_LIS2DH=y
CONFIG_LIS2DH_TRIGGER_NONE=y

# Enable serial
CONFIG_SERIAL=y

# Enable USB Device Stack
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_USB_DEVICE_PRODUCT="Pulse"
CONFIG_USB_DEVICE_MANUFACTURER="Kothari"
CONFIG_USB_DEVICE_VID=0x0483
CONFIG_USB_DEVICE_PID=0x5740

# Enable USB CDC ACM Class
CONFIG_USB_CDC_ACM=y

# Enable console for printk output
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable Flash and NVS for persistent storage
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Enable CRC for data validation
CONFIG_CRC=y

# Enable kernel features
CONFIG_EVENTS=y

# Enable FPU
CONFIG_FPU=y
CONFIG_FPU_SHARING=y

CONFIG_CLOCK_CONTROL=y

CONFIG_MAIN_STACK_SIZE=2048
# Use newlib instead of the minimal libc
CONFIG_NEWLIB_LIBC=y

# 2. Configure the toolchain to use FPU
# Zephyr usually sets this automatically with CONFIG_FPU=y, but
# explicitly setting it ensures correctness if the toolchain defaults are wrong.
CONFIG_HEAP_MEM_POOL_SIZE=2048

CONFIG_FP_HARDABI=y
